### ISSUE TITLE
安装依赖时提示无法安装httpx

### ISSUE THREAD

**Issue by harbor66** [xtaodada/PagerMaid-Modify#12]
环境谷歌云香港 Ubuntu16.04LTS
ERROR: Could not find a version that satisfies the requirement httpx==0.13.3 (from googletrans->-r requirements.txt
 (line 14)) (from versions: none)
ERROR: No matching distribution found for httpx==0.13.3 (from googletrans->-r requirements.txt (line 14))

**Comment by xtaodada** [comment]
@harbor66 请确认 python 版本为 3.6+

**Comment by harbor66** [comment]
谷歌云香港 Ubuntu18.04LTS
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/var/lib/pagermaid/pagermaid/__init__.py", line 6, in <module>
    from yaml import load, FullLoader
ImportError: cannot import name 'FullLoader'

**Comment by xtaodada** [comment]
@harbor66 #1
